name: batchiq_app
description: "A Flutter app for efficient batch management, offering tools to organize, track, and analyze tasks with ease."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  http: ^1.2.2
  intl: ^0.20.1
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2
  hugeicons: ^0.0.7
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/outline_icons/
    - assets/icons/filed_colorful_icons/
    - assets/app_logos/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logos/batch-iq-logo.jpg"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/app_logos/batch-iq-logo.jpg"
  adaptive_icon_background: "#ffffff"
